In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.DataFrame({'inputvalue':[100,110,120,130,140,300,150,160,170,180,190,200]})

In [3]:
df

inputvalue
0          100
1          110
2          120
3          130
4          140
5          300
6          150
7          160
8          170
9          180
10         190
11         200

In [4]:
df.isnull().sum()

inputvalue    0
dtype: int64

In [5]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
inputvalue   12.0  162.5  53.619026  100.0  127.5  155.0  182.5  300.0

In [6]:
(df.isnull().sum()/df.shape[0])*100

inputvalue    0.0
dtype: float64

In [7]:
df['inputvalue'].mean()

np.float64(162.5)

In [8]:
df['inputvalue'].std()

np.float64(53.61902647381804)

## Z-Score (Statistical Method) :-

In [9]:
df['z_score']=(df['inputvalue']-df['inputvalue'].mean())/df['inputvalue'].std()
threshold=2
df['z_anomaly']=abs(df['z_score'])>threshold
df['z_anomaly']

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11    False
Name: z_anomaly, dtype: bool

## IQR (Interquartile Rang) :-

In [10]:
Q1=df['inputvalue'].quantile(0.25)
Q3=df['inputvalue'].quantile(0.75)

IQR=Q3-Q1

lower_limit=Q1-(1.5*IQR)
upper_limit=Q3+(1.5*IQR)

df['iqr_anomaly']=(df['inputvalue']<lower_limit) | (df['inputvalue']>upper_limit)
df[df['iqr_anomaly']==True]

inputvalue   z_score  z_anomaly  iqr_anomaly
5         300  2.564388       True         True

## Isolation Forest() :-

In [11]:
from sklearn.ensemble import IsolationForest

islf=IsolationForest(contamination=0.03,random_state=42)
islf.fit(df)
pred=islf.predict(df)
print(pred)

[ 1  1  1  1  1 -1  1  1  1  1  1  1]


## One-Class SVM() :-

In [12]:
from sklearn.svm import OneClassSVM

ocs=OneClassSVM(gamma='scale',nu=0.17)
ocs.fit(df)
pred_svm=ocs.predict(df)
print(pred_svm)

[-1 -1  1  1  1 -1  1  1  1  1  1  1]


## DBScan() :-

In [14]:
from sklearn.cluster import DBSCAN

dbs=DBSCAN(eps=3,min_samples=2)
pred_db=dbs.fit_predict(df)

anomaly_dbs=[i for i,label in enumerate(pred_db) if label==-1]
anomaly_dbs

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# PyOD() :-

In [16]:
from pyod.models.knn import KNN

knn_py=KNN()
knn_py.fit(df)
pred_knn=knn_py.labels_
print(pred_knn)

[0 0 0 0 0 1 0 0 0 0 0 0]
