# Numpy:-

In [1]:
import numpy as np

In [2]:
num=np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
type(num)

numpy.ndarray

In [6]:
num.ndim

1

In [10]:
num.argmax()

np.int64(9)

In [13]:
num.shape

(10,)

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])